"""add recurring income fields

Revision ID: recurring_income_001
Revises: ed25e18663a1
Create Date: 2026-05-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'recurring_income_001'
down_revision = 'ed25e18663a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(20), nullable=False, server_default='one-time'))
        batch_op.add_column(sa.Column('category', sa.String(80), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('category')
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
